handouts/04/230412/database_05/01_template/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_pk>/follow/', views.follow, name='follow'), 
]

handouts/04/230412/database_05/01_template/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    

handouts/04/230412/database_05/01_template/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

handouts/04/230412/database_05/01_template/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
#
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST, require_safe, require_http_methods
from .forms import CustomUserCreationForm, CustomUserChangeForm


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index') 
    else:
        form = CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['POST'])
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('articles:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index') 
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'accounts/update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index') 
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/change_password.html', context)

@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated():
        person = get_user_model().objects.get(pk=user_pk)
        if person != request.user:
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

handouts/04/230412/database_05/01_template/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호변경</h1>
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="변경하기">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

handouts/04/230412/database_05/01_template/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

handouts/04/230412/database_05/01_template/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ person.username }}님의 프로필</h1>
  <div>
    팔로잉 : {{ person.following.count }} | 팔로워 : {{ person.followers.count }}
  </div>
  <form action="{% url 'accounts:follow' person.pk %}" method='POST'>
    {% csrf_token %}
    {% if request.user in person.followers.all %}
      <button type='submit' class='btn btn-danger'>언팔로우</button>
    {% else %}
     <button type='submit' class='btn btn-success'>팔로우</button>
    {% endif %}

  </form>
  <hr>

  <h5>{{ person.username }}님이 작성한 게시글</h5>
  {% for article in person.article_set.all %}
    <div class='card'>
        <div class='card-body'>
            <h5 class='card-title'>{{ article.title }}</h5>
            <p class='card-text'>{{ article.content }}</p>
            <a href="{% url 'articles:detail' articles.pk %}" class='btn btn-primary'>자세히 보기</a>
        </div>
    </div>  
  
  <a href="{% url 'articles.detail' article.pk %}">{{ article.title }}</a>  

  {% endfor %}
  <hr><br><br>

  <h5>{{ person.username }}님이 좋아한 게시글</h5>
  {% for article in person.like_articles.all %}
  <div class='card'>
      <div class='card-body'>
          <h5 class='card-title'>{{ article.title }}</h5>
          <p class='card-text'>{{ article.content }}</p>
          <a href="{% url 'articles:detail' articles.pk %}" class='btn btn-primary'>자세히 보기</a>
      </div>
  </div>  

<a href="{% url 'articles.detail' article.pk %}">{{ article.title }}</a>  

{% endfor %}
<hr><br><br>
  <a href="{% url 'articles:index' %}" class='btn btn=success'>목록보기</a>



{% endblock content %}

handouts/04/230412/database_05/01_template/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="회원가입">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

handouts/04/230412/database_05/01_template/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원정보수정</h1>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정하기">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}